name: build and publish app
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  ci-build-ppp:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout repo
      uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: set up docker buildx
      uses: docker/setup-buildx-action@v1

    - name: cache docker layers
      uses: actions/cache@v2
      with:
        path: .buildx-cache
        key: $-buildx-$
        restore-keys: |
          $-buildx-

    - name: build and run tests
      run: ./cicd-all.sh
      env:
        MUGSHOT_ZIP_PASSWORD: ${{ secrets.MUGSHOT_ZIP_PASSWORD }}

    - name: move docker layer cache
      run: |
        rm -rf .buildx-cache
        mv .buildx-cache-new .buildx-cache