name: build and publish app
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  ci-build-ppp:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout repo
      uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: restore cached bazel
      id: cache-bazel-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          .bazel
        key: ${{ runner.os }}-bazel

    - name: build and run tests
      run: ./cicd-all.sh
      env:
        MUGSHOT_ZIP_PASSWORD: ${{ secrets.MUGSHOT_ZIP_PASSWORD }}

    - name: save bazel cache
      id: cache-bazel-save
      uses: actions/cache/save@v3
      with:
        path: |
          .bazel
        key: ${{ steps.cache-bazel-restore.outputs.cache-primary-key }}